name: karigarsethu
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1
  flutter_svg: ^2.3.0
  intl: ^0.20.3
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  record: ^7.1.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.7
  image: ^4.10.1
  pro_image_editor: ^14.3.0
  image_cropper: ^12.2.1
  background_remover: ^0.0.3
  google_mlkit_subject_segmentation: ^0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo.jpeg
    - .env

dependency_overrides:
  path_provider_android: 2.2.14
  background_remover:
    path: packages/background_remover

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_padded.jpeg"
  adaptive_icon_background: "#FAF7F2"
  adaptive_icon_foreground: "assets/logo_padded.jpeg"

flutter_native_splash:
  color: "#FAF7F2"
  color_dark: "#1E1E1E"
  image: "assets/logo_padded.jpeg"
  android: true
  ios: true
